plugins {
    id 'com.android.application'
}

android {
    namespace 'com.animwall.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.animwall.app"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation 'com.google.mediapipe:tasks-vision:latest.release'
}
